# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d9028b5e0cd940d1b10bb1efbe62b2705a35fe0cb8d9185d952f277bce852e116e1258e99492cc42be30c1dfa5dbd69bdcdb8f900a2ae1c797de266332c0304

test:
  secret_key_base: cc0073bcb2ea15aa19b909d3fe7069b6fdac29caae2a0c2e95f1f76010a5cf5ddcc558bb71ff8322e3ace9cb158a58c9392dae2adf6e114ad176de64bcc52f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
